const fs = require('fs');
const path = 'src/screens/MemoScreen.tsx';
const src = fs.readFileSync(path, 'utf8');
const count = (s, ch) => (s.split(ch).length - 1);
console.log('backticks', count(src, '`'));
console.log('open', count(src, '{'));
console.log('close', count(src, '}'));
console.log('parensOpen', count(src, '('));
console.log('parensClose', count(src, ')'));
const type = require('typescript');
const sf = type.createSourceFile(path, src, type.ScriptTarget.Latest, true, type.ScriptKind.TSX);
console.log('diagnostics', sf.parseDiagnostics.map(d=>({message: d.messageText, start: type.getLineAndCharacterOfPosition(sf, d.start).line+1, character: type.getLineAndCharacterOfPosition(sf, d.start).character+1})).slice(0,20));
